spring:
  datasource:
    url: jdbc:cockroachdb://localhost:26257/orders?sslmode=disable&retryTransientErrors=true
    driver-class-name: io.cockroachdb.jdbc.CockroachDriver
    username: root
    password:
